package com.mobilefork.hermesagent.ui.i18n

internal fun sharedFolderCopyText(language: AppLanguage, key: String): String {
    val rows = when (language) {
        AppLanguage.CHINESE -> listOf("复制共享文件夹到工作区", "正在复制文件夹…", "文件夹授权不是文件系统挂载。选择文件夹后会创建独立的工作区副本供终端使用。重复复制不会覆盖已有文件；更改不会自动同步回原文件夹。", "复制完成", "复制失败；没有发布不完整的副本", "撤销授权不会删除已导入的副本。每次最多复制 512 MiB、10,000 个条目和 32 层目录；大文件夹请选择子文件夹。", "取消复制")
        AppLanguage.SPANISH -> listOf("Copiar carpeta al espacio de trabajo", "Copiando carpeta…", "El permiso no monta un sistema de archivos. Al seleccionar una carpeta se crea una copia independiente para el terminal. Repetir la copia no sobrescribe archivos existentes; los cambios no se sincronizan con el original.", "Copia terminada", "La copia falló; no se publicó una copia incompleta", "Revocar el acceso no elimina las copias importadas. Límite por copia: 512 MiB, 10.000 entradas y 32 niveles. Para carpetas grandes, selecciona una subcarpeta.", "Cancelar copia")
        AppLanguage.GERMAN -> listOf("Ordner in Arbeitsbereich kopieren", "Ordner wird kopiert…", "Eine Freigabe ist kein Dateisystem-Mount. Die Ordnerauswahl erstellt eine separate Kopie für das Terminal. Erneutes Kopieren überschreibt keine vorhandenen Dateien; Änderungen werden nicht zurücksynchronisiert.", "Kopie abgeschlossen", "Kopieren fehlgeschlagen; keine unvollständige Kopie veröffentlicht", "Das Entziehen der Freigabe löscht keine importierten Kopien. Je Kopie höchstens 512 MiB, 10.000 Einträge und 32 Ebenen. Für größere Ordner einen Unterordner wählen.", "Kopieren abbrechen")
        AppLanguage.PORTUGUESE -> listOf("Copiar pasta para a área de trabalho", "Copiando pasta…", "A permissão não monta um sistema de arquivos. Selecionar uma pasta cria uma cópia independente para o terminal. Repetir a cópia não sobrescreve arquivos existentes; alterações não são sincronizadas com o original.", "Cópia concluída", "A cópia falhou; nenhuma cópia incompleta foi publicada", "Revogar o acesso não exclui cópias importadas. Limite por cópia: 512 MiB, 10.000 itens e 32 níveis. Para pastas grandes, selecione uma subpasta.", "Cancelar cópia")
        AppLanguage.FRENCH -> listOf("Copier le dossier dans l’espace de travail", "Copie du dossier…", "L’autorisation ne monte pas de système de fichiers. Choisir un dossier crée une copie indépendante pour le terminal. Une nouvelle copie n’écrase pas les fichiers existants ; les modifications ne sont pas resynchronisées avec l’original.", "Copie terminée", "Échec de la copie ; aucune copie incomplète publiée", "Révoquer l’accès ne supprime pas les copies importées. Limite par copie : 512 Mio, 10 000 entrées et 32 niveaux. Pour les grands dossiers, choisissez un sous-dossier.", "Annuler la copie")
        AppLanguage.ENGLISH -> listOf("Copy shared folder to workspace", "Copying folder…", "A folder grant is not a filesystem mount. Selecting a folder creates a separate workspace copy for terminal tools. Repeated copies never overwrite existing files; changes do not sync back to the original folder.", "Copy complete", "Copy failed; no incomplete copy was published", "Clearing access does not delete imported copies. Each copy is limited to 512 MiB, 10,000 entries and 32 levels; choose a subfolder for larger folders.", "Cancel copy")
    }
    val index = listOf("copy", "busy", "help", "done", "failed", "limits", "cancel").indexOf(key)
    require(index >= 0) { "Unknown shared-folder label: $key" }
    return rows[index]
}
